name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v4
      - name: build and tests
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
          npm test