name: CI

on:
  push:
    branches:
      - "main"
    paths: [ 'hangman-api/**' ]
  pull_request:
    branches: [main]
    paths: [ 'hangman-api/**' ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: build and tests
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
          npm test