name: CI

on:
  push:
    branches:
      - "main"
    paths: [ 'hangman-api/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'hangman-api/**' ]

jobs:
  build-test:
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, ubuntu-20.04]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: build and tests
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
          npm test